### PR TITLE
Additional Whitelist options

### PR DESCRIPTION
**Pull request by ndoriot**
I have made the following updates.

1. Added additional whitelist options so that the tools can be better utilized from a CI/CD scenario since the blacklist will not have to be constantly updated if updates are made to OOB and 3rd party solutions in CE.

1. Updated the connection string setting to allow a full connection string to be specified and used.

1. Updated the nuspec file for the API project to fix the .NET framework version to 4.5.2 since that it what it is built against and should support.  Also changed the tools to be included as content so they get added to the project and they don't have to manually be copied.

### CODE REVIEW

**Comment by daryllabar** [comment]
Thanks for the PR.  I have a question on item 3... with the change of the SDK being on 4.6.2 ( [.net 4.6.2 is now required as a baseline](https://www.nuget.org/packages/Microsoft.CrmSdk.CoreAssemblies/)), shouldn't it be set as 4.6.2?  I'd rather force people on an older version to either choose to update to the latest version of the SDK, or manually have to fix it, rather than those on the latest and greatest having to do more work, or am I not understanding the issue?

Would also be interested in a write up of how you're using the API, since I made that mostly just for Scott Durow's Sparkle Framework,

**Comment by ndoriot** [comment]
I don't disagree with the 4.6.2 comment and would be fine if that was excluded.  I am still in the habit of building my solutions against 4.5.2 to some extent as I still have some environments that would require it until clients get on the latest version.  In my current usage, I can upgrade to use 4.6.2 so it is not a huge deal. 

As far as the usage, I am generating early bound types for our project with an automated build from Dev Ops.  Without the whitelist, this includes way too many entities and it constantly has to be updated as Microsoft pushes out core CE updates and of course Field Services, etc. updates.  With the automated build in place we can have all of our early bound types published to a Dev Ops feed for consumption in all our other codes bases.

**Comment by ndoriot** [comment]
One other note on the nuget spec however, I do think it makes sense to include the files as content to avoid needing to copy them so the tools and API assembly can be used.

**Comment by daryllabar** [comment]
I have repushed the Nuget Files.  Saw your note on the Actions where it was removing the prefixes... this was due to me not knowing how to query for the logical name of the action, and using the unique name of the Workflow.  I fixed this in the UI, and removed the prefix removal logic from the crmsvcutil.  It may break some API people, but it was a poor solution, and the fix is pretty simple, just to add the prefixes...

**Pull request merged**
