### PR TITLE
Adds vendor folder, makes project CI-friendly.

### PR DESCRIPTION
**Pull request by skfd**
Adds some sweet binaries.

### CODE REVIEW

**Comment by skfd** [comment]
You can now setup [Appveyor](www.appveyor.com), so it will check all the commits and pull requests. Here's my fork being build successfully: https://ci.appveyor.com/project/skfd/dlab-xrm-xrmtoolboxtools/history

**Comment by daryllabar** [comment]
Thanks @Skfd !  I'm using AppVoyer in my unit testing project, and hadn't gotten around to doing it in this project yet.  Give me a few days to accept everything and setup appvoyer.  I'm hoping Monday or Tuesday while I'm at extremeCrm

**Comment by daryllabar** [comment]
I fixed the reference error that I had, and Have a successful Appveyor build going.  I probably need to update this to use the NuGet References to the Dlls, or maybe make one for the XrmToolBox, and then use that.

**Comment by skfd** [comment]
You need to add the Team Foundation stuff, too.

You are distributing those `dll`s in the release, so there's no reason not to include it in project.

**Comment by daryllabar** [comment]
Added Thanks!

**Pull request closed without merging**
